#!/bin/bash

echo == Deployment
curl -w '\n' -X POST --connect-timeout 2 -D - \
  -H "Content-type: application/json" \
  -d @deliver-module-deploy.json  \
  http://localhost:9130/_/deployment/modules         || exit

echo == Proxy
curl -w '\n' -X POST --connect-timeout 2 -D - \
    -H "Content-type: application/json"   \
    -d @deliver-module-proxy.json \
   http://localhost:9130/_/proxy/modules             || exit

echo == Create tenant
curl -w '\n' -X POST --connect-timeout 2 -D - \
  -H "Content-type: application/json" \
  -d '{  "id" : "hbz", "name" : "hbz",  "description" : "Hochschulbibliothekszentrum" }' \
  http://localhost:9130/_/proxy/tenants              || exit

echo == Enable module for tenant
curl -w '\n' -X POST --connect-timeout 2 -D - \
  -H "Content-type: application/json" \
  -d '{ "id" : "hbz-deliver-module" }' \
  http://localhost:9130/_/proxy/tenants/hbz/modules  || exit




