#!/bin/bash

echo -- Deployment
curl -w '\n' -X POST -D - \
  -H "Content-type: application/json" \
  -d @deliver-module-deploy.json  \
  http://localhost:9130/_/deployment/modules

echo -- Proxy
curl -w '\n' -X POST -D -   \
    -H "Content-type: application/json"   \
    -d @deliver-module-proxy.json \
   http://localhost:9130/_/proxy/modules

echo -- Create tenant
curl -w '\n' -X POST -D - \
  -H "Content-type: application/json" \
  -d '{  "id" : "hbz", "name" : "hbz",  "description" : "Hochschulbibliothekszentrum" }' \
  http://localhost:9130/_/proxy/tenants

echo -- Enable module for tenant
curl -w '\n' -X POST -D - \
  -H "Content-type: application/json" \
  -d '{ "id" : "hbz-deliver-module" }' \
  http://localhost:9130/_/proxy/tenants/hbz/modules

